version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: Postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: accounts
    ports:
      - "5432:5432"
    networks:
      - container_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  hands-on-api:
    image: hands-on-dev-api  # Imagem já buildada ou buildada via context abaixo
    container_name: hands-on-dev-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=Postgres;Port=5432;Database=accounts;Username=root;Password=root1234"
    networks:
      - container_network

networks:
  container_network:
    driver: bridge

volumes:
  pgdata:
