//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartOfAccounts.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChartOfAccounts.CrossCutting.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código {0} já existe..
        /// </summary>
        public static string Validation_ChartOfAccounts_CodeAlreadyExists {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_CodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código &apos;{0}&apos; não possui o código &apos;{1}&apos; como pai. O código da conta deve começar com o código do pai seguido por um ponto..
        /// </summary>
        public static string Validation_ChartOfAccounts_CodeMustStartWithParent {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_CodeMustStartWithParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código {0} não foi encontrado..
        /// </summary>
        public static string Validation_ChartOfAccounts_CodeNotFound {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir o plano de contas com código &apos;{0}&apos; porque ele possui contas filhas. Você deve excluir todas as contas filhas primeiro..
        /// </summary>
        public static string Validation_ChartOfAccounts_HasChildren {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_HasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código {0} não existe ou não é um código pai válido..
        /// </summary>
        public static string Validation_ChartOfAccounts_InvalidParentCode {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_InvalidParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tipo da conta &apos;{2}&apos; deve ser o mesmo que o tipo da conta pai &apos;{0}&apos; que é &apos;{1}&apos;..
        /// </summary>
        public static string Validation_ChartOfAccounts_InvalidParentType {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_InvalidParentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código {0} não aceita contas filhas pois ele permite lançamentos..
        /// </summary>
        public static string Validation_ChartOfAccounts_ParentIsPostable {
            get {
                return ResourceManager.GetString("Validation_ChartOfAccounts_ParentIsPostable", resourceCulture);
            }
        }
    }
}
